[build]
builder = "DOCKERFILE"
dockerfilePath = "VirtualMuseum.API/Dockerfile"

[deploy]
startCommand = "dotnet VirtualMuseum.API.dll"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
