// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualMuseum.Infrastructure.Data;

#nullable disable

namespace VirtualMuseum.Infrastructure.Migrations
{
    [DbContext(typeof(MuseumDbContext))]
    [Migration("20260316152948_ConfirmAdminEmail")]
    partial class ConfirmAdminEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Depth")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("DiscoveryLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EraId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModelFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DiscoveryLocationId");

                    b.HasIndex("EraId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ModelFileId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("ThumbnailFileId");

                    b.ToTable("Artifacts", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.ToTable("ArtifactEmbeddings", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEmbeddingSource")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.ToTable("ArtifactMedia", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactTag", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ArtifactId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArtifactTags", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HistoricalStory")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.ToTable("ArtifactTranslations", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("UserId");

                    b.ToTable("ArtifactViews", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatMessageArtifact", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId", "ArtifactId");

                    b.HasIndex("ArtifactId");

                    b.ToTable("ChatMessageArtifacts", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.DiscoveryLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("DiscoveryLocations", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.EmailOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("EmailOtps", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Era", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Eras", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.MuseumFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Artifact", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Category", "Category")
                        .WithMany("Artifacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualMuseum.Domain.Entities.User", "Creator")
                        .WithMany("CreatedArtifacts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualMuseum.Domain.Entities.DiscoveryLocation", "DiscoveryLocation")
                        .WithMany("Artifacts")
                        .HasForeignKey("DiscoveryLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualMuseum.Domain.Entities.Era", "Era")
                        .WithMany("Artifacts")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualMuseum.Domain.Entities.Material", "Material")
                        .WithMany("Artifacts")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualMuseum.Domain.Entities.MuseumFile", "ModelFile")
                        .WithMany()
                        .HasForeignKey("ModelFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VirtualMuseum.Domain.Entities.MuseumFile", "ThumbnailFile")
                        .WithMany()
                        .HasForeignKey("ThumbnailFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("DiscoveryLocation");

                    b.Navigation("Era");

                    b.Navigation("Material");

                    b.Navigation("ModelFile");

                    b.Navigation("ThumbnailFile");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactEmbedding", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany("Embeddings")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactMedia", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany("Media")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactTag", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany("ArtifactTags")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualMuseum.Domain.Entities.Tag", "Tag")
                        .WithMany("ArtifactTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactTranslation", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany("Translations")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ArtifactView", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany("ArtifactViews")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualMuseum.Domain.Entities.User", "User")
                        .WithMany("ArtifactViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Artifact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatMessageArtifact", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualMuseum.Domain.Entities.ChatMessage", "Message")
                        .WithMany("Artifacts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany("Favorites")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualMuseum.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Review", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Artifact", "Artifact")
                        .WithMany("Reviews")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualMuseum.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.User", b =>
                {
                    b.HasOne("VirtualMuseum.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Artifact", b =>
                {
                    b.Navigation("ArtifactTags");

                    b.Navigation("ArtifactViews");

                    b.Navigation("Embeddings");

                    b.Navigation("Favorites");

                    b.Navigation("Media");

                    b.Navigation("Reviews");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Category", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatMessage", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.DiscoveryLocation", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Era", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Material", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ArtifactTags");
                });

            modelBuilder.Entity("VirtualMuseum.Domain.Entities.User", b =>
                {
                    b.Navigation("ArtifactViews");

                    b.Navigation("ChatSessions");

                    b.Navigation("CreatedArtifacts");

                    b.Navigation("Favorites");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
